services:
  - type: web
    name: latex-compiler
    runtime: docker
    dockerfilePath: ./Dockerfile.production
    plan: free # upgrade to 'starter' for $7/month for more resources
    healthCheckPath: /health
    region: oregon # or ohio, virginia, frankfurt, singapore
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TECTONIC_CACHE_DIR
        value: /tmp/tectonic-cache
    autoDeploy: true # Auto-deploy on git push
    buildCommand: "" # Docker handles the build
    startCommand: "" # Defined in Dockerfile